apiVersion: apps/v1 
kind: Deployment  
metadata: 
    name: mydeployment 
    labels: 
       app: deployment 
       type: frontend 
spec: 
   replicas: 4
   strategy:
       type: RollingUpdate
   selector: 
       matchExpressions: 
            -  key: app 
               operator: In 
               values: 
                  - myapp1
            -  key: type 
               operator: NotIn  
               values: 
                  - backend 
                  - fe

   template: 
      metadata: 
          labels: 
             app: myapp1
      spec: 
         containers: 
            - name: nginx 
              image: nginx 
            - name: mybe 
              image: tomcat