apiVersion: v1
kind: Pod
metadata:
     name: mymeta
     labels:
       app: myapp1 
       type: frontend 
spec:
    containers:
         - name: mynginx
           image: nginx
           ports: 
              - containerPort: 80