apiVersion: v1 
kind: ReplicationController 
metadata: 
   name: repli 
   labels:
      app: rclabel 
      type: frontend 
spec: 
   replicas: 3
   selector:
       app: myapp1
   template:
      metadata:
         labels:
            app: myapp1
      spec: 
         containers:
            - name: nginxcont
              image: nginx